name: Release CI
on:
  push:
    branches:
      - master
      - beta

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install deps
        run: pnpm install

      - name: Test
        run: pnpm run test

  release:
    needs: test
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # npm 8 和 9 会在 `npm version` 时执行依赖树命令，进而报错退出
      # Refs: https://github.com/semantic-release/npm/issues/540
      - name: Setup npm 7
        run: npm i -g npm@7 --registry=https://registry.npmjs.org

      - name: Install deps
        run: pnpm install

      - name: release
        run: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
